### ISSUE TITLE
License

### ISSUE THREAD

**Issue by silverhook** [Ergodox-io/ergodox-io#1]
GPL doesn’t make much sense for non-code content. I’d suggest using either CC-BY-4.0 (non-copyleft) or CC-BY-SA-4.0 (copyleft) for the website itself.

… what the code powering the website is licensed under doesn’t affect the content of the website :smile:

**Comment by robotmaxtron** [comment]
I think you're right, CC-BY-4.0 (non-copyleft) I think makes the most sense

**Comment by robotmaxtron** [comment]
Changed in 1c2520704a71436f26ab59479bffce92592e0b35

**Comment by silverhook** [comment]
:+1:
