### ISSUE TITLE
Ortholinear or vertically staggered?

### ISSUE THREAD

**Issue by algernon** [Ergodox-io/ergodox-io#26]
The intro section says: `laid out in an ortholinear (rather than staggered) layout` - it is not ortholinear, it is column-staggered. Ortholinear would mean that there is no stagger at all, in any direction, anywhere, which is not the case for the original ErgoDox, and not the case for most of the common variants, either.

I would suggest replacing the text with something like:

`laid out in a columnar stagger (rather than the more conventional row stagger) layout`

**Comment by robotmaxtron** [comment]
You are  absolutely correct. I'll get this fixed soon, thank you.

**Comment by robotmaxtron** [comment]
Fixed in https://github.com/Ergodox-io/ergodox-io/commit/59eac0fcf6949b01ece500dc2ae191b06e948468#diff-dcc920e5ec022b1bc40138b87159ffcdR175
