### ISSUE TITLE
How does one test the board before soldering switches?

### ISSUE THREAD

**Issue by stkrzysiak** [Ergodox-io/ergodox-io#57]
Hey all, 
I noticed in an [alternate guide](http://imgur.com/a/3riAB)  robotmaxtron says it's a good idea to test before soldering the switches.  How does someone go about doing this? I'd be happy to submit a PR with this info, once I know how ;)

**Comment by robotmaxtron** [comment]
@stkrzysiak once all of the electronics besides the switches are installed, flash a default .hex file or a known working one (I can link you one of mine) and plug everything in. 

Take a pair of tweezers and short each pin to ensure that a number or letter appears. I typically use Aqua's keytester but any text editor will work.

I hope this helps.

**Comment by stkrzysiak** [comment]
Perfect, thank you @robotmaxtron!
