### ISSUE TITLE
Contact Dox regarding the original ErgoDox.org website

### ISSUE THREAD

**Issue by silverhook** [Ergodox-io/ergodox-io#9]
@doxkb ([Dominic “Dox” Beauchamp][dox]) is the initial author of ErgoDox and its original website. It would be great to get in contact with him to:

- let him know about ErgoDox.org not being available and the new ErgoDox.io website
- ask him as the (previous?) owner of ergodox.org to unlock the [site’s archive][ia] at the Internet Archive
- get content from him if he has a backup anywhere
- get his blessing for the new website and comments on it

Neither of these are needed, as long as we comply with his original license, but it would be very good form from our side.

[dox]: https://github.com/doxkb
[ia]: https://web.archive.org/web/http://ergodox.org/

**Comment by robotmaxtron** [comment]
I've sent a couple emails that have gone unanswered as well. I'll leave the issue up for a bit, but based on the domain expiring and the unanswered emails, I don't expect a response.

**Comment by silverhook** [comment]
I hoped that referring him in the issue might get his attention.

**Comment by robotmaxtron** [comment]
Closing, there's been no movement from the original designers. They (and anybody) is welcome to create pull requests, issues and request membership to the Ergodox-io organization on github.
